const List<Map<String, dynamic>> drEssaLaboratory = [
  {
    "id": 1,
    "laboratory": "Dr. Essa's laboratory (Zamzama Centre)",
    "city": "Karachi",
    "address":
        "Suite# 2, Plot 8-C, (Besides Aijaz Boutique) 4th  Zamzama Comercial Lane,",
    "serviceAgiantItsLocation": "-",
    "contact": "35376887",
  },
  {
    "id": 2,
    "laboratory": "Dr. Essa's laboratory (Medilink Centre)",
    "city": "Karachi",
    "address":
        "Suite# 103, 1st  Floor, The Plazaq, 2 Talwar, Khayaban-e-Iqbal, Main Clifton Road",
    "serviceAgiantItsLocation": "-",
    "contact": "35376071-74",
  },
  {
    "id": 3,
    "laboratory": "Dr. Essa's laboratory (Abul Hassan Isphahani Centre)",
    "city": "Karachi",
    "address":
        "A-1/3, Block-4, Gulishan-e-Iqbal, Main Abul Hassan Isphahani Road",
    "serviceAgiantItsLocation": "-",
    "contact": "3496377-78",
  },
  {
    "id": 4,
    "laboratory": "Dr. Essa's laboratory (Ayesha Manzil Centre)",
    "city": "Karachi",
    "address": "Suite# CS19/02, Block 7, Ali Appartments, F.B. Area",
    "serviceAgiantItsLocation": "-",
    "contact": "36312746",
  },
  {
    "id": 5,
    "laboratory": "Dr. Essa's laboratory (Gulistan-e-Jauhar Centre)",
    "city": "Karachi",
    "address": "S B 1, Suit#2, Javed Arcade, Block 17, Gulistan-e-Jauhar",
    "serviceAgiantItsLocation": "-",
    "contact": "34620176",
  },
  {
    "id": 6,
    "laboratory": "Dr. Essa's laboratory (Gulshan Centre)",
    "city": "Karachi",
    "address":
        "FL-3/9, Ground Floor, Block-5, Main Rashid Minhas Road, Near Mr. Burger",
    "serviceAgiantItsLocation": "-",
    "contact": "34994616",
  },
  {
    "id": 7,
    "laboratory": "Dr. Essa's laboratory",
    "city": "Karachi",
    "address": "B-122, Block-H, Shahra-e-Jehangir, North Nazimabad,",
    "serviceAgiantItsLocation": "-",
    "contact": "36626125-26",
  },
  {
    "id": 8,
    "laboratory": "Dr. Essa's laboratory (Hussainabad Centre)",
    "city": "Karachi",
    "address":
        "Suite#2, Plot#, 480, Block-2 Sadiqabad, F.B. Area, Memon Colony,",
    "serviceAgiantItsLocation": "-",
    "contact": "36320136",
  },
  {
    "id": 9,
    "laboratory": "Dr. Essa's laboratory (Civil Hospital Centre)",
    "city": "Karachi",
    "address": "Suite#1-3, Asif Square, Baba-e-Urdu Road, Opp. Civil Hospital",
    "serviceAgiantItsLocation": "-",
    "contact": "32768132",
  },
  {
    "id": 10,
    "laboratory": "Dr. Essa's laboratory (Safoora Centre)",
    "city": "Karachi",
    "address":
        "Billy's Arcade, Suite# 145-146, Main University Road, KDA Scheme 33,",
    "serviceAgiantItsLocation": "-",
    "contact": "34650077",
  },
  {
    "id": 11,
    "laboratory": "Dr. Essa's laboratory (Shah Faisal Centre)",
    "city": "Karachi",
    "address":
        "A1 Building, A1 Chowk, Near UBL Bank, Naseerabad, Shah Faisal Colony",
    "serviceAgiantItsLocation": "-",
    "contact": "34686222",
  },
];

const List<Map<String, dynamic>> chughtaiLaboratory = [
  {
    "id": 1,
    "laboratory": "Chugtai's laboratory",
    "city": "Karachi",
    "address":
        "Al-Khaleej Tower, Shaheed-e-Millat Road, Near Medicare Hospital, Shop # 1, Karachi.",
    "serviceAgiantItsLocation": "-",
    "contact": "021-111-255-790 Mobile# 0332-1424249",
  },
  {
    "id": 2,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "10-Jail Raod, Main Gulberg Lahore",
    "serviceAgiantItsLocation": "-",
    "contact": "042 3571 0730 042 3571 1711",
  },
  {
    "id": 3,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "257-Rewaz Garden, Lahore",
    "serviceAgiantItsLocation": "-",
    "contact": "042 3717 1085",
  },
  {
    "id": 4,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "Opp. Main Emergency Gate Services Hospital",
    "serviceAgiantItsLocation": "-",
    "contact": "3458402867",
  },
  {
    "id": 5,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "Main Bazar Makkah Colony Street# 05",
    "serviceAgiantItsLocation": "-",
    "contact": "None",
  },
  {
    "id": 6,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "115.1-B 2, Khokhar Chowk, Al-Janat Merrige Hall",
    "serviceAgiantItsLocation": "-",
    "contact": "3214595431",
  },
  {
    "id": 7,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "National Hospital 132-L Block DHA, Lahore",
    "serviceAgiantItsLocation": "-",
    "contact": "042 3573 0582",
  },
  {
    "id": 8,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "08-Jail Raod, Main Gulberg Lahore",
    "serviceAgiantItsLocation": "-",
    "contact": "042 3571 0730 042 3571 1711",
  },
  {
    "id": 9,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "4 Gulshan Block, Main Boulevard, Allama Iqbal Town, Lahore",
    "serviceAgiantItsLocation": "-",
    "contact": "3458494210",
  },
  {
    "id": 10,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "Shalimar Link Road, Opp: Shalimar Hospital, Lahore",
    "serviceAgiantItsLocation": "-",
    "contact": "042 3684 8475",
  },
  {
    "id": 11,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "368 GT Road Opp. S.A. Rehman Factory Stop,",
    "serviceAgiantItsLocation": "-",
    "contact": "None",
  },
  {
    "id": 12,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "260 - GT Road, Rasheed Clinic",
    "serviceAgiantItsLocation": "-",
    "contact": "3458445042",
  },
  {
    "id": 13,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "Sharif Market, Main Walton Road, Lahore",
    "serviceAgiantItsLocation": "-",
    "contact": "042 3666 2921",
  },
  {
    "id": 14,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "Main Samanabad More, Lahore",
    "serviceAgiantItsLocation": "-",
    "contact": "042 3746 3862 042 3740 1447",
  },
  {
    "id": 15,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "Opp. Milan Shadi Hall, Moon Market",
    "serviceAgiantItsLocation": "-",
    "contact": "3009393905",
  },
  {
    "id": 16,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "Behind Sir, Ganga Ram Hospital",
    "serviceAgiantItsLocation": "-",
    "contact": "3458494215",
  },
  {
    "id": 17,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "Care Clinic, 13-M, Block, DHA",
    "serviceAgiantItsLocation": "-",
    "contact": "0344 44 8974",
  },
  {
    "id": 18,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "Dubai Chowk Saddar Lahore",
    "serviceAgiantItsLocation": "-",
    "contact": "3458449392",
  },
  {
    "id": 19,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "Hafeez Poly Hospital, Nespak Colony, Lahore",
    "serviceAgiantItsLocation": "-",
    "contact": "042 3518 0212",
  },
  {
    "id": 20,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "Opp. Emergency Gate, Mayo Hospital, Lahore",
    "serviceAgiantItsLocation": "-",
    "contact": "3444449151",
  },
  {
    "id": 21,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "Near Baba Shatri Wala Darbar, Ravi Road",
    "serviceAgiantItsLocation": "-",
    "contact": "3444448961",
  },
  {
    "id": 22,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "39-Commercial Area, Cavalry Ground,",
    "serviceAgiantItsLocation": "-",
    "contact": "3458435416",
  },
  {
    "id": 23,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "103-Allama Iqbal Road, Ghari Shahu, Lahore",
    "serviceAgiantItsLocation": "-",
    "contact": "3458494216",
  },
  {
    "id": 24,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "20 - M Gulberg-3, Naseerabad Stop, Near Ghulab Devi Hospital,",
    "serviceAgiantItsLocation": "-",
    "contact": "3454712776",
  },
  {
    "id": 25,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "Opp: Back Gate,Sheikh Zayed Hospital, Lahore",
    "serviceAgiantItsLocation": "-",
    "contact": "3066134861",
  },
  {
    "id": 26,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "Main Wahdat Road, Opp: Abrar Centre, Lahore",
    "serviceAgiantItsLocation": "-",
    "contact": "3458402870",
  },
  {
    "id": 27,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "456-G-4, Johar Town, Khokhar Chowk, Lahore",
    "serviceAgiantItsLocation": "-",
    "contact": "042 3616 8562",
  },
  {
    "id": 28,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "513-A Faisal Town, Opp: Jinnah Hospital Lahore",
    "serviceAgiantItsLocation": "-",
    "contact": "042 3517 5670",
  },
  {
    "id": 29,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "PECO Road, Near Link Road Model Town.",
    "serviceAgiantItsLocation": "-",
    "contact": "None",
  },
  {
    "id": 30,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "Liver Clinic, Shadman",
    "serviceAgiantItsLocation": "-",
    "contact": "3458495762",
  },
  {
    "id": 31,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "Opp. Fatima Memorial Hospital, Shadman",
    "serviceAgiantItsLocation": "-",
    "contact": "3458440350",
  },
  {
    "id": 32,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "Multan Chungi, Opp: Mansooran Hospital, Lahore",
    "serviceAgiantItsLocation": "-",
    "contact": "042 3541 9525",
  },
  {
    "id": 33,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "Awan Town, Multan Road",
    "serviceAgiantItsLocation": "-",
    "contact": "3235513030",
  },
  {
    "id": 34,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "154-B West Wood, Raiwind Road,Thokar Niaz Baig,",
    "serviceAgiantItsLocation": "-",
    "contact": "042 3596 3037",
  },
  {
    "id": 35,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "Main Buleward DHA, Near Adil Hospital",
    "serviceAgiantItsLocation": "-",
    "contact": "3014983160",
  },
  {
    "id": 36,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "Adil Hasan Medical Complex, Q-Block DHA",
    "serviceAgiantItsLocation": "-",
    "contact": "3458435416",
  },
  {
    "id": 37,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "Ayesha Hospital, Nishat Colony",
    "serviceAgiantItsLocation": "-",
    "contact": "3024079300",
  },
  {
    "id": 38,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "Opp: Ghurki Hospital, Jallo, Lahore",
    "serviceAgiantItsLocation": "-",
    "contact": "3458440342",
  },
  {
    "id": 39,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "Opp: Rangers Head Quarter, Lahore",
    "serviceAgiantItsLocation": "-",
    "contact": "3219477279",
  },
  {
    "id": 40,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "34-Y Block, DHA",
    "serviceAgiantItsLocation": "-",
    "contact": "042 3573 1687",
  },
  {
    "id": 41,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "Hameeda Memorial Hospital, Valancia Town",
    "serviceAgiantItsLocation": "-",
    "contact": "3458402878",
  },
  {
    "id": 42,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "114-Abdali Road, Near Farhan Hospital, Islampura",
    "serviceAgiantItsLocation": "-",
    "contact": "3458494212",
  },
  {
    "id": 43,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "Bank Square Market, C-Block Model Town",
    "serviceAgiantItsLocation": "-",
    "contact": "3444448971",
  },
  {
    "id": 44,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "Opp. National Hospital, Chowk Nakhuda,",
    "serviceAgiantItsLocation": "-",
    "contact": "042 3774 5440",
  },
  {
    "id": 45,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "chowk choubuji",
    "serviceAgiantItsLocation": "-",
    "contact": "3458445095",
  },
  {
    "id": 46,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "shahdara cener near Allied Bank",
    "serviceAgiantItsLocation": "-",
    "contact": "3454004750",
  },
  {
    "id": 47,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "REVENUE MEDICAL CENTER LAHORE",
    "serviceAgiantItsLocation": "-",
    "contact": "3455556029",
  },
  {
    "id": 48,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "Lahore General  Hospital Center",
    "serviceAgiantItsLocation": "-",
    "contact": "3454005427",
  },
  {
    "id": 49,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "Taj Bagh Lahore",
    "serviceAgiantItsLocation": "-",
    "contact": "3454004691",
  },
  {
    "id": 50,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "Liaqat Chowk, Near Kashmir Bazar, Sabzazar,",
    "serviceAgiantItsLocation": "-",
    "contact": "3214964339",
  },
  {
    "id": 51,
    "laboratory": "Chugtai's laboratory",
    "city": "Gujranwala",
    "address": "Munir Chowk, Near Civil Hospital, Gujranwala",
    "serviceAgiantItsLocation": "-",
    "contact": "553859398",
  },
  {
    "id": 55,
    "laboratory": "Chugtai's laboratory",
    "city": "Alipur Chatha",
    "address": "Madina Chowk, Hafizabad Road, Ali Pur Chatta Dist Gujran",
    "serviceAgiantItsLocation": "-",
    "contact": "556404285",
  },
  {
    "id": 53,
    "laboratory": "Chugtai's laboratory",
    "city": "Wazirabad",
    "address": "Opp. Civil Hospital, Wazirabad Dist Gujran",
    "serviceAgiantItsLocation": "-",
    "contact": "556605858",
  },
  {
    "id": 54,
    "laboratory": "Chugtai's laboratory",
    "city": "Daska",
    "address": "Opp. Civil Hospital, Near Qazi Medical Store, Daska",
    "serviceAgiantItsLocation": "-",
    "contact": "526611627",
  },
  {
    "id": 55,
    "laboratory": "Chugtai's laboratory",
    "city": "Narowal",
    "address": "Al-Muzamil Palaza, Kachery Road, Narowal",
    "serviceAgiantItsLocation": "-",
    "contact": "542413488",
  },
  {
    "id": 56,
    "laboratory": "Chugtai's laboratory",
    "city": "Hafizabad",
    "address": "Dak-Khana Road, Hafizabad",
    "serviceAgiantItsLocation": "-",
    "contact": "547541436",
  },
  {
    "id": 57,
    "laboratory": "Chugtai's laboratory",
    "city": "Muridkey",
    "address": "Zafar Arcade, GT Road, Muridke",
    "serviceAgiantItsLocation": "-",
    "contact": "0300-9493378",
  },
  {
    "id": 58,
    "laboratory": "Chugtai's laboratory",
    "city": "Kamonki",
    "address": "Main Bazar, Ali Garh Road, Kamonki",
    "serviceAgiantItsLocation": "-",
    "contact": "3007401546",
  },
  {
    "id": 59,
    "laboratory": "Chugtai's laboratory",
    "city": "Farooqabad",
    "address": "Mian Road, Farooqabad",
    "serviceAgiantItsLocation": "-",
    "contact": "0345-4100356",
  },
  {
    "id": 60,
    "laboratory": "Chugtai's laboratory",
    "city": "Gujrat",
    "address": "Bimber Road, Near Cheema Hospital",
    "serviceAgiantItsLocation": "-",
    "contact": "053 360 5738 053 303 0435",
  },
  {
    "id": 61,
    "laboratory": "Chugtai's laboratory",
    "city": "Kharian",
    "address": "Basement United Bank, Main GT Road,",
    "serviceAgiantItsLocation": "-",
    "contact": "053 753 5982 053 753 2635",
  },
  {
    "id": 62,
    "laboratory": "Chugtai's laboratory",
    "city": "Lala Musa",
    "address": "Niazi Hospital, Near Sabzi Mandi, Main GT Road,",
    "serviceAgiantItsLocation": "-",
    "contact": "053-751 0787",
  },
  {
    "id": 63,
    "laboratory": "Chugtai's laboratory",
    "city": "Abbottabad",
    "address": "C-B 733 Amir Plaza, Near Ayub Medical Complex, Nowshehra Road,",
    "serviceAgiantItsLocation": "-",
    "contact": "0992 544 255 0992 383 377",
  },
  {
    "id": 64,
    "laboratory": "Chugtai's laboratory",
    "city": "Mansehra",
    "address": "Al-Rahim Plaza, Opp. King Abdullah Hospital",
    "serviceAgiantItsLocation": "-",
    "contact": "None",
  },
  {
    "id": 65,
    "laboratory": "Chugtai's laboratory",
    "city": "Haripur",
    "address": "1 Doctors Plaza, Circular Road,",
    "serviceAgiantItsLocation": "-",
    "contact": "995611446",
  },
  {
    "id": 66,
    "laboratory": "Chugtai's laboratory",
    "city": "Gujranwala",
    "address": "Chaudhry Hospital, 28-D Satellite Town,",
    "serviceAgiantItsLocation": "-",
    "contact": "055 373 5514 055 373 5211",
  },
  {
    "id": 67,
    "laboratory": "Chugtai's laboratory",
    "city": "Sheikhupura",
    "address": "Near Khawar Hospital, Sargodha Road, Sheikhuura",
    "serviceAgiantItsLocation": "-",
    "contact": "3454100356",
  },
  {
    "id": 68,
    "laboratory": "Chugtai's laboratory",
    "city": "Kasur",
    "address": "Railway Road, Kasur",
    "serviceAgiantItsLocation": "-",
    "contact": "3464541440",
  },
  {
    "id": 69,
    "laboratory": "Chugtai's laboratory",
    "city": "Okara",
    "address": "Tehseel Road, Opp: Press Club, Okara",
    "serviceAgiantItsLocation": "-",
    "contact": "0442-528 450",
  },
  {
    "id": 70,
    "laboratory": "Chugtai's laboratory",
    "city": "Sahiwal",
    "address": "Mall Mandi Chowck, Near Dr. Khawar Clinic",
    "serviceAgiantItsLocation": "-",
    "contact": "3454004695",
  },
  {
    "id": 71,
    "laboratory": "Chugtai's laboratory",
    "city": "Faisalabad",
    "address": "Saleemi Chowk, Sityana Road, Faisalabad",
    "serviceAgiantItsLocation": "-",
    "contact": "3458402874",
  },
  {
    "id": 72,
    "laboratory": "Chugtai's laboratory",
    "city": "Vehari",
    "address": "Jinnah Road, Vehari",
    "serviceAgiantItsLocation": "-",
    "contact": "3217720360",
  },
  {
    "id": 73,
    "laboratory": "Chugtai's laboratory",
    "city": "Chichawatni",
    "address": "Block#14, Girls College Road",
    "serviceAgiantItsLocation": "-",
    "contact": "405003481",
  },
  {
    "id": 74,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "Main Buleward DHA, Near Adil Hospital",
    "serviceAgiantItsLocation": "-",
    "contact": "3014983160",
  },
  {
    "id": 75,
    "laboratory": "Chugtai's laboratory",
    "city": "Depalpur",
    "address": "Depalpur Medical Complex, Kachery Road",
    "serviceAgiantItsLocation": "-",
    "contact": "3009446569",
  },
  {
    "id": 76,
    "laboratory": "Chugtai's laboratory",
    "city": "Peshawar",
    "address": "Doctors Plaza, Shop#23,Opp. Hayatabad Medical Complex,",
    "serviceAgiantItsLocation": "-",
    "contact": "3458402877",
  },
  {
    "id": 77,
    "laboratory": "Chugtai's laboratory",
    "city": "Jhung",
    "address": "Near DHQ Hospital, Gojra Road,",
    "serviceAgiantItsLocation": "-",
    "contact": "3216500188",
  },
  {
    "id": 78,
    "laboratory": "Chugtai's laboratory",
    "city": "Bahawalpur",
    "address": "Opp: Bahawal Victoria Hospital, Bahawalpur",
    "serviceAgiantItsLocation": "-",
    "contact": "3156335717",
  },
  {
    "id": 79,
    "laboratory": "Chugtai's laboratory",
    "city": "Rajanpur",
    "address": "Kachehry Road, Near Dr. Noshaba Hospital",
    "serviceAgiantItsLocation": "-",
    "contact": "3219710001",
  },
  {
    "id": 80,
    "laboratory": "Chugtai's laboratory",
    "city": "Arifwala",
    "address": "19-C Block, Main Landa Bazar, Arifwala",
    "serviceAgiantItsLocation": "-",
    "contact": "457412294",
  },
  {
    "id": 81,
    "laboratory": "Chugtai's laboratory",
    "city": "Sambrial",
    "address": "Near Maqi Masjid, GT Road,",
    "serviceAgiantItsLocation": "-",
    "contact": "3006166913",
  },
  {
    "id": 82,
    "laboratory": "Chugtai's laboratory",
    "city": "Quetta",
    "address": "Faiz Muhammad Street, Jinnah Road",
    "serviceAgiantItsLocation": "-",
    "contact": "812837719",
  },
  {
    "id": 83,
    "laboratory": "Chugtai's laboratory",
    "city": "Sialkot",
    "address": "Church Road, Sialkot",
    "serviceAgiantItsLocation": "-",
    "contact": "523561212",
  },
  {
    "id": 84,
    "laboratory": "Chugtai's laboratory",
    "city": "Sargodha",
    "address": "Near Sarwar Hospital, Satellite Town, Sargodha",
    "serviceAgiantItsLocation": "-",
    "contact": "483223011",
  },
  {
    "id": 85,
    "laboratory": "Chugtai's laboratory",
    "city": "Khanewal",
    "address": "Block# 15, Stadium Road, Khanewal",
    "serviceAgiantItsLocation": "-",
    "contact": "658030780",
  },
  {
    "id": 86,
    "laboratory": "Chugtai's laboratory",
    "city": "Layyah",
    "address": "College Road, Layyah",
    "serviceAgiantItsLocation": "-",
    "contact": "0606 317 506 0606 413 957",
  },
  {
    "id": 87,
    "laboratory": "Chugtai's laboratory",
    "city": "Bahawalnagar",
    "address": "Opp. DHQ Hospital, Bahawalnagar",
    "serviceAgiantItsLocation": "-",
    "contact": "63800059",
  },
  {
    "id": 88,
    "laboratory": "Chugtai's laboratory",
    "city": "Hasilpur",
    "address": "Baldia Road, Hasilpur",
    "serviceAgiantItsLocation": "-",
    "contact": "3334387539",
  },
  {
    "id": 89,
    "laboratory": "Chugtai's laboratory",
    "city": "Haroonabad",
    "address": "Opp. Civil Hospital, Haroonabad",
    "serviceAgiantItsLocation": "-",
    "contact": "06322 50 805",
  },
  {
    "id": 90,
    "laboratory": "Chugtai's laboratory",
    "city": "Kabirwala",
    "address": "Saleem Medical Hall, Near Pul Rajbah",
    "serviceAgiantItsLocation": "-",
    "contact": "3214784926",
  },
  {
    "id": 91,
    "laboratory": "Chugtai's laboratory",
    "city": "Manga Mandi",
    "address": "Opp. Al-Nasir Clinic, Hospital Road,",
    "serviceAgiantItsLocation": "-",
    "contact": "3454309944",
  },
  {
    "id": 92,
    "laboratory": "Chugtai's laboratory",
    "city": "Islamabad",
    "address": "Royal Centre, Fazal-e-Haq Road, Blue Area, Islamabad",
    "serviceAgiantItsLocation": "-",
    "contact": "3444443099",
  },
  {
    "id": 93,
    "laboratory": "Chugtai's laboratory",
    "city": "Rawalpindi",
    "address": "Holy Family Hospital, Opp. Gate#03,",
    "serviceAgiantItsLocation": "-",
    "contact": "3444443099",
  },
  {
    "id": 94,
    "laboratory": "Chugtai's laboratory",
    "city": "Renalakhurd",
    "address": "Opp. Welcome Gate GT Road, renalakhurd",
    "serviceAgiantItsLocation": "-",
    "contact": "3024528197",
  },
  {
    "id": 95,
    "laboratory": "Chugtai's laboratory",
    "city": "Pattoki",
    "address": "Opp. Sarwar Sajid Hospital, Main GT Road",
    "serviceAgiantItsLocation": "-",
    "contact": "494421124",
  },
  {
    "id": 96,
    "laboratory": "Chugtai's laboratory",
    "city": "Bur-e-Wala",
    "address": "Bur-e-Wala Hospital, Bur-e-Wala",
    "serviceAgiantItsLocation": "-",
    "contact": "3458494212",
  },
  {
    "id": 97,
    "laboratory": "Chugtai's laboratory",
    "city": "Chishtian",
    "address": "Dr. Ismail Shaheed Road, Highway Road,",
    "serviceAgiantItsLocation": "-",
    "contact": "632501904",
  },
  {
    "id": 98,
    "laboratory": "Chugtai's laboratory",
    "city": "Sadiqabad",
    "address": "Hospital Road, Sadiqabad",
    "serviceAgiantItsLocation": "-",
    "contact": "3009633865",
  },
  {
    "id": 99,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "Bank Square Market, C-Block Model Town",
    "serviceAgiantItsLocation": "-",
    "contact": "3444448971",
  },
  {
    "id": 100,
    "laboratory": "Chugtai's laboratory",
    "city": "Lahore",
    "address": "Opp. National Hospital, Chowk Nakhuda,",
    "serviceAgiantItsLocation": "-",
    "contact": "042 3774 5440",
  },
  {
    "id": 101,
    "laboratory": "Chugtai's laboratory",
    "city": "Joharabad",
    "address": "Saadi Market, Khalid Chowck,",
    "serviceAgiantItsLocation": "-",
    "contact": "0454  720 011",
  },
  {
    "id": 102,
    "laboratory": "Chugtai's laboratory",
    "city": "Multan",
    "address": "Dost Plaza, Nisther Road, Multan",
    "serviceAgiantItsLocation": "-",
    "contact": "3458401294",
  },
  {
    "id": 103,
    "laboratory": "Chugtai's laboratory",
    "city": "Mian Channu",
    "address": "Shaheed Road, Sadam Chowck, Mian Channu",
    "serviceAgiantItsLocation": "-",
    "contact": "0652-668 577",
  },
  {
    "id": 104,
    "laboratory": "Chugtai's laboratory",
    "city": "Pakpattan",
    "address": "None",
    "serviceAgiantItsLocation": "-",
    "contact": "3008086249",
  },
  {
    "id": 105,
    "laboratory": "Chugtai's laboratory",
    "city": "Chakwal",
    "address": "Asif Medical Hall, Opp. DHQ Hospital, Jehlum Road",
    "serviceAgiantItsLocation": "-",
    "contact": "3224554784",
  },
  {
    "id": 106,
    "laboratory": "Chugtai's laboratory",
    "city": "Shujabad",
    "address": "None",
    "serviceAgiantItsLocation": "-",
    "contact": "614396793",
  },
  {
    "id": 107,
    "laboratory": "Chugtai's laboratory",
    "city": "Sindh",
    "address": "shah ghazi Muhala Near Imam Medical center",
    "serviceAgiantItsLocation": "-",
    "contact": "0722-653803",
  },
  {
    "id": 108,
    "laboratory": "Chugtai's laboratory",
    "city": "Zahir Peer",
    "address": "Main Chowck, Zahir Peer",
    "serviceAgiantItsLocation": "-",
    "contact": "455563007",
  },
  {
    "id": 109,
    "laboratory": "Chugtai's laboratory",
    "city": "Bur-e-Wala",
    "address": "Near DHQ Hospital, Stadium Road Bur-e- Wala",
    "serviceAgiantItsLocation": "-",
    "contact": "673770113",
  },
  {
    "id": 110,
    "laboratory": "Chugtai's laboratory",
    "city": "Sindh",
    "address": "Ladies Jail Road, Near Amber X-Rays, Larkana.",
    "serviceAgiantItsLocation": "-",
    "contact": "0345-8406650",
  },
];

const List<Map<String, dynamic>> jpCtCentre = [
  {
    "id": 1,
    "laboratory": "JP's CT,MRI,MRS",
    "city": "Karachi",
    "address": "Hilal-e-Ahmer,Teen Talwar,Clifton",
    "serviceAgiantItsLocation": "-",
    "contact": "2135306061",
  },
  {
    "id": 2,
    "laboratory": "JP's CT Scan & Diagnostic",
    "city": "Karachi",
    "address": "APWA Complex,Garden Road,Opposite IBA",
    "serviceAgiantItsLocation": "-",
    "contact": "2132226156",
  },
  {
    "id": 3,
    "laboratory": "JP's CT Scan Center",
    "city": "Karachi",
    "address": "Chandni Chowk near New Town,Liaquat national Hospital",
    "serviceAgiantItsLocation": "-",
    "contact": "2134932441",
  },
  {
    "id": 4,
    "laboratory": "JP's CT Scan Center-2",
    "city": "Karachi",
    "address": "Malir Kalaboard",
    "serviceAgiantItsLocation": "-",
    "contact": "3214494353",
  },
  {
    "id": 5,
    "laboratory": "DRC,MIR,MRA Scan Center",
    "city": "Karachi",
    "address": "ISM Building,opp.Ankle Saria Hospital,Garden Road",
    "serviceAgiantItsLocation": "-",
    "contact": "-",
  },
];

const List<Map<String, dynamic>> islamabadDiagnosticlaboratory = [
  {
    "id": 1,
    "laboratory": "Islamabad Diagnostic Centre (Head Office)",
    "city": "Islamabad",
    "address": "13-A, Kohistan Road, F-8 Markaz, Islamabad",
    "serviceAgiantItsLocation":
        "All laboratory and Imaging (Radiology) tests/test profiles, Radiology and Cardiology Procedures including Out Source (TDL, UK) & (Synlab, Germany) tests/test Profiles.",
    "contact": "051-2251212, 2263737, 2263939",
  },
  {
    "id": 2,
    "laboratory": "Islamabad Diagnostic Centre",
    "city": "Islamabad",
    "address":
        "Capital Trade Centre, Adjacent to Paprika,F 10 Markaz, Islamabad",
    "serviceAgiantItsLocation": "All laboratory Services only",
    "contact": "051-2223080  0343-8530010 0343-8530010",
  },
  {
    "id": 3,
    "laboratory": "Islamabad Diagnostic Centre",
    "city": "Islamabad",
    "address": "Federation Plaza, E 11/2, Islamabad",
    "serviceAgiantItsLocation": "All laboratory Services X Rays Ultrasound ECG",
    "contact": "Tel: 051 230 5325 Mobile:0300 0451632 0343 8530017",
  },
  {
    "id": 4,
    "laboratory": "Islamabad Diagnostic Centre",
    "city": "Islamabad",
    "address":
        "Zam Zam  Arcade Plot = 3- B G 13/1 Opp Rahat Bakers Near UBL Bank and Allied Bank, Islamabad",
    "serviceAgiantItsLocation": "All laboratory Services X Rays Ultrasound ECG",
    "contact": "Tel: 051 874 4205 Mobile: 0343 8530013",
  },
  {
    "id": 5,
    "laboratory": "Islamabad Diagnostic Centre",
    "city": "Islamabad",
    "address":
        "Silver city Plaza, Shop No. B – 1, Basement Soneri Bank, G 11 Markaz, Islamabad",
    "serviceAgiantItsLocation": "All laboratory Services X Rays Ultrasound ECG",
    "contact": "Tel: 051 236 3370 Mobile: 0343 8530011",
  },
  {
    "id": 6,
    "laboratory": "Islamabad Diagnostic Centre",
    "city": "Islamabad",
    "address":
        "Ground Floor  Adjacent Bake man Bakers Near HBL Bank, G 10 Markaz, Islamabad",
    "serviceAgiantItsLocation": "All laboratory Services",
    "contact": "Tel: 051 235 3322 Mobile: 0343 8530018",
  },
  {
    "id": 7,
    "laboratory": "Islamabad Diagnostic Centre",
    "city": "Islamabad",
    "address":
        "Zam Zam Arcade, Shop #01 ,Basement UBL And Near Allied BankG 15 Markaz, # 31,32 & 33,IBslaasmeambeandt Awami Trade",
    "serviceAgiantItsLocation": "All laboratory Services",
    "contact": "Tel: 051 230 8328 Mobile: 0343-8530015",
  },
  {
    "id": 8,
    "laboratory": "Islamabad Diagnostic Centre",
    "city": "Islamabad",
    "address": "Centre,G-9 Markaz (Karachi Company),Islamabad",
    "serviceAgiantItsLocation": "All laboratory Services X Rays Ultrasound ECG",
    "contact": "Tel: 051 285 3737 Mobile: 0343 850009",
  },
  {
    "id": 9,
    "laboratory": "Islamabad Diagnostic Centre",
    "city": "Islamabad",
    "address": "12 M Square G 8 Markaz, Islamabad",
    "serviceAgiantItsLocation":
        "All laboratory Services CT ScanGamma Camera X Rays Fluoroscopy OPG Ultrasound ECG",
    "contact": "Tel: 051 234 0275-6 Mobile:0343 8530005",
  },
  {
    "id": 10,
    "laboratory": "Islamabad Diagnostic Centre",
    "city": "Islamabad",
    "address":
        "city Square L ground floor Block B Gate no 1 Multi Gardeb=n, Islamabad",
    "serviceAgiantItsLocation": "All laboratory Services",
    "contact": "Tel: 051 5203017 Mobile: 0343 8530014",
  },
  {
    "id": 11,
    "laboratory": "Islamabad Diagnostic Centre",
    "city": "Islamabad",
    "address":
        "Plot No. 35, Office No. 8, Ground Floor, Ahmed Centre Sector I-8 Markaz,",
    "serviceAgiantItsLocation": "All laboratory Services Ultrasound X Rays",
    "contact": "Tel: 051 486 4884 Mobile:0343 8530020",
  },
  {
    "id": 12,
    "laboratory": "Islamabad Diagnostic Centre",
    "city": "Islamabad",
    "address": "Khyber Plaza, Blue Area, (Near D.Watson) Islamabad",
    "serviceAgiantItsLocation": "All laboratory Services only",
    "contact": "Tel: 051 280 4226 Mobile: 0343 8530021",
  },
  {
    "id": 13,
    "laboratory": "Islamabad Diagnostic Centre",
    "city": "Islamabad",
    "address":
        "Huma Plaza, Near Al-Rehman  Masjid,Opposite OG DC Building, Blue Area,Ansab Towar AIs-la7m,DaHbAadPhase 02 Gate",
    "serviceAgiantItsLocation": "All laboratory Services Ultrasound",
    "contact": "Tel: 051 227 7244Mobile:0343 8530007",
  },
  {
    "id": 14,
    "laboratory": "Islamabad Diagnostic Centre",
    "city": "Islamabad",
    "address":
        "Ansab Towar A- 7,DHA Phase 02 Gate #01,Ground Near JS Bank And Subway Main G.T Road ",
    "serviceAgiantItsLocation": "All Laboratory Services only",
    "contact": "Tel: 051 516 1985, Mobile: 0343 8530023",
  },
  {
    "id": 16,
    "laboratory": "Islamabad Diagnostic Centre",
    "city": "Islamabad",
    "address": "Classic centre, Ground Floor, D-17 Markaz Islamabad",
    "serviceAgiantItsLocation": "All laboratory Services",
    "contact": "Tel: 051 216 9110Mobile: 0343 8530025",
  },
  {
    "id": 17,
    "laboratory": "Islamabad Diagnostic Centre",
    "city": "Islamabad",
    "address":
        "Ground Floor Near Allied Bank , Opposite Suzuki Motors I-9 Markaz Islamabad",
    "serviceAgiantItsLocation": "All laboratory Services",
    "contact": "Mobile: 0343 8530028",
  },
  {
    "id": 18,
    "laboratory": "Islamabad Diagnostic Centre",
    "city": "Islamabad",
    "address":
        "Ground Floor Abdullah Plaza, Ghouri Town Phase 5-B Near Garden Chowk",
    "serviceAgiantItsLocation": "All laboratory Services",
    "contact": "Mobile: 0343 8530027",
  },
  {
    "id": 19,
    "laboratory":
        "Dr. Aslam Uppal Diagnostic Centre (Wah Cantt.) (Subsidiary of IDC)",
    "city": "Lalazar wah cantt",
    "address": "3-Quaid Avenue, Near Aslam Uppal Square, Lalazar wah Cantt.",
    "serviceAgiantItsLocation":
        "All laboratory Services MRI CTScan DEXA Scan X Rays X Ray Procedures X Ray Mammography Ultrasound ECG & Echo",
    "contact": "Tel: 0514-511 765, 533599 Mobile: 03015029090",
  },
  {
    "id": 20,
    "laboratory": "Islamabad Diagnostic Centre",
    "city": "Gujar Khan",
    "address": "Opposite Nadra Office Barki Morr Main GT Road Gujar Khan",
    "serviceAgiantItsLocation": "All laboratory Services",
    "contact": "Mobile: 0343 8530029",
  },
  {
    "id": 21,
    "laboratory": "Islamabad Diagnostic Centre",
    "city": "Rawalpindi",
    "address": "Saidpur Road, Rawalpindi",
    "serviceAgiantItsLocation": "All laboratory Services DEXA Scan X Rays",
    "contact": "Tel: 051 835 4484Mobile: 0343 8530014",
  },
  {
    "id": 22,
    "laboratory": "Islamabad Diagnostic Centre",
    "city": "Rawalpindi",
    "address": "Near Chandni Chowk Allied Bank Main Murree Road Rawalpindi",
    "serviceAgiantItsLocation":
        "All laboratory Services MRI CT Scan Ultrasound  X Rays Dexa Spiro",
    "contact": "Tel: 051 426 4141 Cell:0343 8530006",
  },
  {
    "id": 23,
    "laboratory": "Islamabad Diagnostic Centre",
    "city": "Rawalpindi",
    "address":
        "Civic Centre, Airport Housing Society, Gulzar e Quaid, Rawalpindi",
    "serviceAgiantItsLocation": "All laboratory Services Ultrasound X Rays ECG",
    "contact": "Tel: 051 570 9902Mobile: 0343 8530012",
  },
  {
    "id": 23,
    "laboratory": "Islamabad Diagnostic Centre",
    "city": "Rawalpindi",
    "address":
        "Sehgal Emporium Office No 1 Ground Floor Near UFone Office Cantonment Board Cantt Murree Road Rawalpindi",
    "serviceAgiantItsLocation": "All laboratory Services  X-Rays",
    "contact": "Tel: 051 552 1212Mobile: 0343 8530019",
  },
  {
    "id": 24,
    "laboratory": "Islamabad Diagnostic Centre",
    "city": "Rawalpindi",
    "address": "Opposite Doctor Colony, PWD, Rawalpindi",
    "serviceAgiantItsLocation":
        "All laboratory Services CT Scan DEXA Scan X Rays OPG Ultrasound ECG & Echo",
    "contact": "Tel: 051 519 4661Mobile: 0343 8530004",
  },
];
